import { NextIntlClientProvider, useMessages } from 'next-intl';
import { Roboto } from 'next/font/google';
import type { Metadata } from 'next';
import '../globals.css';
import { Header } from '@/components/layout';
import { ThemeProvider } from '@/components/Provider/Theme/theme-provider';
import { ReactQueryClientProvider } from '@/components/Provider/ReactQuery/react-query-provider';

const roboto = Roboto({
  style: 'normal',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  const messages = useMessages();

  return (
    <html lang={locale}>
      <body className={roboto.className}>
        <ReactQueryClientProvider>
          <NextIntlClientProvider messages={messages}>
            <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
              <main className='max-w-4xl mx-auto p-4'>
                <Header locale={locale} />

                {children}
              </main>
            </ThemeProvider>
          </NextIntlClientProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
