import { NextIntlClientProvider, useMessages } from 'next-intl';
import { Roboto } from 'next/font/google';
import type { Metadata } from 'next';
import '../globals.css';
import { Header, ThemeProvider } from '@/components/MyComponents';
import { getLocale } from 'next-intl/server';

const roboto = Roboto({
  style: 'normal',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  const messages = useMessages();
  // let locale = ''
  // (async() => {
  //   locale = await getLocale();

  // })


  return (
    <html lang={locale}>
      <body className={roboto.className}>
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
      <Header locale={locale} />

            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
